### ISSUE TITLE
网页下载能否做个basic验证，防止外网用户打开这个网页恶意访问 下载

### ISSUE THREAD

**Issue by zcmi** [gngpp/nas-xunlei#14]
关联这个issue：https://github.com/cnk3x/xunlei/issues/57

**Comment by gngpp** [comment]
![image](https://user-images.githubusercontent.com/51810656/236628249-c775353f-3c0b-4766-a9ad-ac21c5f53374.png)
![image](https://user-images.githubusercontent.com/51810656/236628272-fa64378a-9cfc-45bb-8566-383ba16f2859.png)

已更新：https://github.com/gngpp/nas-xunlei/releases/tag/v3.5.2-4
