### ISSUE TITLE
勾选了启用还是提示未运行

### ISSUE THREAD

**Issue by xiaowenlv** [gngpp/nas-xunlei#19]
没看懂怎么添加任务，一直显示未运行

**Comment by gngpp** [comment]
你是怎么装的？我测了几台机器都没问题

**Comment by gngpp** [comment]
版本发我看一下，opkg list-installed | grep xunlei

**Comment by gngpp** [comment]
> 版本发我看一下，opkg list-installed | grep xunlei

启停一点问题都没有
<img width="1033" alt="image" src="https://user-images.githubusercontent.com/51810656/236105351-a512c634-6c2f-4b94-8a34-88be4db48526.png">

**Comment by xiaowenlv** [comment]
/tmp$ opkg list-installed | grep xunlei
luci-app-xunlei - 1.0.1-2
luci-i18n-xunlei-zh-cn - 1.0.1-2
xunlei - 3.5.2-1
启动之后几秒钟就变成未运行了，也没看到什么报错信息。

**Comment by gngpp** [comment]
> /tmp$ opkg list-installed | grep xunlei luci-app-xunlei - 1.0.1-2 luci-i18n-xunlei-zh-cn - 1.0.1-2 xunlei - 3.5.2-1 启动之后几秒钟就变成未运行了，也没看到什么报错信息。

https://github.com/gngpp/nas-xunlei/releases/tag/v3.5.2-3 请更新下载

**Comment by gngpp** [comment]
> /tmp$ opkg list-installed | grep xunlei luci-app-xunlei - 1.0.1-2 luci-i18n-xunlei-zh-cn - 1.0.1-2 xunlei - 3.5.2-1 启动之后几秒钟就变成未运行了，也没看到什么报错信息。

先卸载，再重新安装最新的，然后ssh执行命令service xunlei disable && service xunlei enable
