### ISSUE TITLE
luci-app-xunlei_1.0.1-5-1_all.ipk 点击启动后还是一直未运行

### ISSUE THREAD

**Issue by yipush** [gngpp/nas-xunlei#30]
不知道是luci哪里有问题，我手动执行/etc/init.d/xunlei start就正常启动和使用了

**Comment by gngpp** [comment]
> 不知道是luci哪里有问题，我手动执行/etc/init.d/xunlei start就正常启动和使用了

执行 service xunlei disable && service xunlei enable

**Comment by yipush** [comment]
> > 不知道是luci哪里有问题，我手动执行/etc/init.d/xunlei start就正常启动和使用了
> 
> 执行 service xunlei disable && service xunlei enable



> > 不知道是luci哪里有问题，我手动执行/etc/init.d/xunlei start就正常启动和使用了
> 
> 执行 service xunlei disable && service xunlei enable

用命令是可以启动，主要是luci不能控制启动和停止，luci无法启动程序也不能关闭

**Comment by Y0J1G3N** [comment]
安装xunlei_3.5.2-9_x86_64.ipk和luci-app-xunlei_1.0.1-5-1_all.ipk有同样的问题

**Comment by gngpp** [comment]
![Screenshot_2023-05-10-20-39-38-297_com.android.chrome.jpg](https://github.com/gngpp/nas-xunlei/assets/51810656/21a211f4-fbec-4b82-a0ce-5f836e21648b)

**Comment by yipush** [comment]
> ![image](https://user-images.githubusercontent.com/51810656/237395637-49828595-474f-4894-8b0b-1f59db31aa30.png) 也不知道你们为啥跑不起来，日志也不发给我

主要是一点日志也没有啊哥，系统日志没有，软件内的日志也没有，要不您发下联系信息，帮忙远程看下呢？

**Comment by gngpp** [comment]
qq发我邮箱gngppz@gmail.com

**Comment by gngpp** [comment]
解决掉一个，还有问题的发q到我邮箱
